token: your token
owners:
  - owner
shards: 1
firstShard: 0
lastShard: 0
prefixes:
  - unique prefix 1
postgres:
  host: db host
  username: db user
  password: db pass
  database: db name
api:
  weebsh: weeb.sh token
  google: google api key